[tool.poetry]
name = "backend"
version = "0.1.0"
description = "Backend for Prgic Vila"
authors = ["Valentin Vareskic"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.78.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
