from fastapi import FastAPI, Request
from .api.v1.router import router
import time

app = FastAPI(
    title="Vila Prgic",
    description="Backend for Vila Prgic site",
    version="0.0.1",
)


@app.middleware("http")
async def add_process_time_header(request: Request, call_next):
    """
    Middleware to adds execution time to
    X-Process-Time header to every request

    Parameters
    ----------
    request: Request
        Request from the API
    call_next: Function
        It will receive the request as a parameter.
        This function will pass the request to the corresponding path operation.
        Then it returns the response generated by the corresponding path operation.

    Returns
    -------
        response: dict
            Response with added time header
    """
    start_time = time.time()
    response = await call_next(request)
    process_time = time.time() - start_time
    response.headers["X-Process-Time"] = str(process_time)
    return response


app.include_router(router, prefix="/api/v1")
